apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/
  - monitoring/
  - nginx/

# add labels for all
commonLabels:
  sandbox: dev
images:
#old image name
- name: postgres 
# new image name
  newName: mysql
# new tag
  newTag: "1.2"
  
 #add annotations for all  
commonAnnotations:
  owner: bob@gmail.com 
